### ISSUE TITLE
是我没安装好python?怎么输出的缓存目录是空的

### ISSUE THREAD

**Issue by Skull-Li** [mbinary/netease-music-cracker#1]
目录是建立了，但是目录是空的

**Comment by heqin-zhu** [comment]
抱歉， 现在才看到

我现在更新了一下， 你再试试？

现在只需要 py3 和 requests 模块

**Comment by NagaruZ** [comment]
出现了同样的问题，py3下已经安装了requests模块，运行后目录内是空的。并且“cached_网易云音乐”目录并不是放在缓存文件夹的父目录下，而是就在缓存文件夹里……

**Comment by heqin-zhu** [comment]
@NagaruZ  你可以发一下截图看看, 我现在更新了,你用最新的版本试的吗

**Comment by NagaruZ** [comment]
刚下载的，应该是最新的……运行时没有报错信息……
![image](https://user-images.githubusercontent.com/6185476/41602891-616fa68a-740e-11e8-9662-524b566b4482.png)

**Comment by heqin-zhu** [comment]
@NagaruZ   你这次运行的, 生成的文件应该放在了 缓存 目录下, 现在我又(‾◡◝)更新了,是放在 缓存目录父目录下, 并且在 readme 中添加了gif 展示,   后面我会考虑生成可执行文件, 方便大家使用

**Comment by NagaruZ** [comment]
首先先感谢你~ 不过我查看 缓存 目录下的“cached_网易云音乐”目录时，仍然是空的…（困惑）
![image](https://user-images.githubusercontent.com/6185476/41603948-975c1510-7410-11e8-9e8d-cf04ee30d5c8.png)

**Comment by heqin-zhu** [comment]
哦哦, 我知道了, 你用的电脑上的, 我还没有找到电脑上的缓存文件在哪里, 以及是否符合这个
解码格式, 所以现在只能拷贝手机上的缓存文件到电脑上再用, 你可以重新读一下 README 😂

给 大家说一下抱歉, 以前没有测试电脑上的, 电脑上的缓存文件不一样.

**Comment by NagaruZ** [comment]
啊，是这样啊……我是从博客来的，那里的原话是说【在手机上的缓存文件在 netease/cloudmusic/Cache/里的Music1里， 歌词在Lyric里，（电脑上的路径可以在设置里找到）】，所以我以为电脑的缓存也可以直接用这个工具了

**Comment by heqin-zhu** [comment]
哦哦, 是呀, 最新更新都在github上, 博客很少更新的,(。・∀・)ノ

**Comment by NagaruZ** [comment]
不妨稍微改一下那篇博客hhh，搜索的时候排名还挺靠前的，这样也可以帮到更多人呀（笑） 给dalao递茶（恭敬）

**Comment by heqin-zhu** [comment]
嗯嗯, 好的

**Comment by qrzbing** [comment]
我提了一个pr，里面的可以用电脑的哦0v0
