### ISSUE TITLE
这个不是issues，是个提问^_^

### ISSUE THREAD

**Issue by gitQqqHs** [mbinary/netease-music-cracker#14]
请问这个是什么文件管理器呢？？？
就是你演示代码的那个文件夹管理器。
![2019-10-17_13-28-29](https://user-images.githubusercontent.com/26195745/66980362-39d4ca80-f0e3-11e9-8b2f-e7309a3af572.png)

**Comment by heqin-zhu** [comment]
Windows 上的 Directory Opus

**Comment by heqin-zhu** [comment]
你是说那个动图吗？  那个是 Windows 上的 WSL
