### ISSUE TITLE
输出文件缺失的问题

### ISSUE THREAD

**Issue by zmx0142857** [mbinary/netease-music-cracker#16]
1. 我的输入含有 100 个 `.uc!` 文件, 但输出的 `.mp3` 只有 85 个, 还有 15 个到哪里去了呢. 如果文件信息解析失败, 是不是提示一下比较好?
2. 运行程序时, 命令行输出有 86 条. 其中两个文件名完全相同. 检查 `.mp3/` 目录, 其中只有 85 个文件. 可能是输出的同名文件发生覆盖? 比如同一首歌有两个版本的情况?

最后, 非常感谢你的分享! 芜湖!

**Comment by heqin-zhu** [comment]
抱歉，这么晚才回复。缺失了的数据不知道具体原因，而且也不好找到成对的，所以不提示为好。因为提示了也解决不了。
