### ISSUE TITLE
请问下输出的文件名称怎么修改，我想改成  歌曲手-歌曲名称.MP3 的这种格式

### ISSUE THREAD

**Issue by lihomeos** [mbinary/netease-music-cracker#17]
请问下输出的文件名称怎么修改，我想改成  歌曲手-歌曲名称.MP3 的这种格式

**Comment by heqin-zhu** [comment]
修改[这一行](https://github.com/heqin-zhu/music-recover/blob/c5c42c243c8076e462521268dd0e44d2fd8ebb80/decrypt.py#LL59C8-L59C40)为 `name = artist + '-' + title`
